"use client";
import { useEffect, useState, type FormEvent } from 'react';
import { Card, CardContent, CardHeader } from '@/components/ui/card';
type Fee = {amount:string;currency:string;basis:'APPLICATION'|'APPLICANT';active:boolean};
export function VisaAssistanceFeePanel() {
 const [fee,setFee]=useState<Fee>({amount:'',currency:'MYR',basis:'APPLICATION',active:false});
 const [loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[message,setMessage]=useState('');
 useEffect(()=>{let active=true;void fetch('/api/b2c/visa/assistance-fee',{cache:'no-store'}).then(async response=>{const json=await response.json();if(!response.ok)throw new Error(json.message||json.error||'Fee settings could not load.');if(active&&json.data)setFee(json.data);}).catch(error=>{if(active)setMessage(error.message);}).finally(()=>{if(active)setLoading(false);});return()=>{active=false;};},[]);
 async function save(event:FormEvent){event.preventDefault();setSaving(true);setMessage('');try{const response=await fetch('/api/b2c/visa/assistance-fee',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(fee)});const json=await response.json();if(!response.ok)throw new Error(json.message||json.error||'Fee could not be saved.');setFee(json.data);setMessage('Fee saved. New checkout orders will use this price.');}catch(error){setMessage(error instanceof Error?error.message:'Fee could not be saved.');}finally{setSaving(false);}}
 return <Card><CardHeader><h3 className="font-bold text-slate-900">Assisted visa service pricing</h3><p className="mt-1 text-sm text-slate-500">Set the service fee customers see before payment. Existing checkout orders keep their quoted price.</p></CardHeader><CardContent>{loading?<p role="status">Loading fee settings…</p>:<form onSubmit={save} className="space-y-4"><div className="grid gap-4 sm:grid-cols-3"><label className="text-xs font-bold text-slate-600">Service fee <span className="text-red-500">*</span><input className="mt-2 w-full rounded-lg border border-slate-200 p-3" required type="number" min="0.01" max="9999999" step="0.01" value={fee.amount} onChange={e=>setFee({...fee,amount:e.target.value})}/></label><label className="text-xs font-bold text-slate-600">Currency<select className="mt-2 w-full rounded-lg border border-slate-200 p-3" value={fee.currency} onChange={e=>setFee({...fee,currency:e.target.value})}>{['MYR','USD','SGD','EUR','GBP','AUD'].map(value=><option key={value}>{value}</option>)}</select></label><label className="text-xs font-bold text-slate-600">Charge basis<select className="mt-2 w-full rounded-lg border border-slate-200 p-3" value={fee.basis} onChange={e=>setFee({...fee,basis:e.target.value as Fee['basis']})}><option value="APPLICATION">Per application</option><option value="APPLICANT">Per applicant</option></select></label></div><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={fee.active} onChange={e=>setFee({...fee,active:e.target.checked})}/>Enable this fee for new checkout orders</label><p className="text-xs text-slate-500">This is Flyseri’s general assistance fee. Destination-specific government fees are not included. Current checkout uses Stripe sandbox payments.</p><button disabled={saving} className="rounded-lg bg-sky-600 px-4 py-2 text-sm font-bold text-white disabled:opacity-50">{saving?'Saving…':'Save visa fee'}</button>{message&&<p role="status" className="text-sm text-slate-600">{message}</p>}</form>}</CardContent></Card>;
}
